# Auto-generated by stage9_realistic_field.sh
# Matches sunflower_field_realistic.sdf
# seed=42 for reproducibility

ALL_FLOWERS = [
    (1.72, 1.95),  # flower_0
    (2.14, 5.44),  # flower_1
    (1.75, 8.75),  # flower_2
    (5.84, 2.24),  # flower_3
    (6.13, 5.67),  # flower_4
    (5.97, 8.54),  # flower_5
    (6.16, 11.95),  # flower_6
    (9.79, 2.56),  # flower_7
    (9.76, 4.99),  # flower_8
    (10.06, 9.14),  # flower_9
    (10.02, 12.72),  # flower_10
    (10.03, 15.82),  # flower_11
    (14.05, 2.33),  # flower_12
    (13.84, 4.99),  # flower_13
    (13.84, 7.87),  # flower_14
    (14.08, 11.27),  # flower_15
    (13.83, 14.4),  # flower_16
    (18.07, 1.85),  # flower_17
    (17.8, 5.48),  # flower_18
    (18.08, 9.23),  # flower_19
]

N_FLOWERS = len(ALL_FLOWERS)

# Sector assignment (by row)
# Rows 0-1 → Drone 0 (LEFT),  Rows 2-3 → Drone 1 (CENTER),  Row 4 → Drone 2 (RIGHT)
SECTOR_FLOWERS = {
    0: [(1.72, 1.95), (2.14, 5.44), (1.75, 8.75), (5.84, 2.24), (5.97, 8.54)],  # Drone 0 LEFT
    1: [(6.13, 5.67), (6.16, 11.95), (9.79, 2.56), (9.76, 4.99), (10.06, 9.14), (10.02, 12.72), (10.03, 15.82)],  # Drone 1 CENTER
    2: [(14.05, 2.33), (13.84, 4.99), (13.84, 7.87), (14.08, 11.27), (13.83, 14.4), (18.07, 1.85), (17.8, 5.48), (18.08, 9.23)],  # Drone 2 RIGHT
}
